site_name: 常振荣的个人网站
site_url: https://sherl-czr.github.io/mkdocs-site/
site_author: 常振荣
site_description: 常振荣的个人网站
nav:
  - Home: index.md
  - 编程:
      - coding/coding.md
  - 游戏:
      - game/game.md
  - 物理教学:
      - physics/8up.md
      - physics/8down.md

theme:
  name: material
  # 后续可以扩展日间模式和夜间模式
  language: zh
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs/
